services:
  xodotnet.mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Randall
      MONGO_INITDB_ROOT_PASSWORD: Tr0ub4dor&3

  xodotnet.postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: xodotnet
  
  xodotnet.rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: incorrect

  xodotnet.main:
    image: xodotnet.main
    build:
      context: .
      dockerfile: XoDotNet.Main/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MainDatabase: Host=xodotnet.postgres;Username=postgres;Password=postgres;Database=xodotnet
      RabbitMQ__Hostname: xodotnet.rabbitmq
      RabbitMQ__Username: username
      RabbitMQ__Password: incorrect
      MongoDatabase__ConnectionString: "mongodb://Randall:Tr0ub4dor&3@xodotnet.mongo:27017/"
    depends_on:
      xodotnet.mongo:
        condition: service_started
      xodotnet.postgres:
        condition: service_started
      xodotnet.rabbitmq:
        condition: service_started
